{
    'name': 'QDV Tarifs Manager',
    'version': '18.0.5.5',
    'category': 'Tools',
    'summary': 'Bases tarifs fournisseurs QDV — familles, remises, dérogations, synchro automatique',
    'depends': ['base', 'product', 'bus'],
    'data': [
        'security/ir.model.access.csv',
        'data/cron.xml',
        'views/tarif_browser_views.xml',
        'views/tarif_base_views.xml',
        'views/tarif_family_views.xml',
        'views/tarif_rebate_views.xml',
        'views/tarif_derogation_views.xml',
        'views/tarif_article_views.xml',
        'views/tarif_cron_views.xml',
        'wizard/import_wizard_views.xml',
        'wizard/import_derogation_wizard_views.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
